#!/usr/bin/env bash
# Copyright 2023 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Script to update the version of the CIPD CLI pinned by Jiri.

set -eu -o pipefail

jiri_dir="$( cd "$( dirname "$( dirname "${BASH_SOURCE[0]}" )" )" >/dev/null && pwd )"

cipd_client_pkg='infra/tools/cipd/${platform}'

# Resolve the latest version of the CIPD CLI. We can't just do `cipd
# selfupdate-roll -version latest` because the "latest" ref might point to a
# different version for different platforms, so instead we resolve the
# git_revision tag of the "latest" version for the current platform and update
# to that tag for all platforms.
versions="$(cipd describe "$cipd_client_pkg" -version latest | grep git_revision)"
versions=($versions)

success=false
# There may be multiple git_revision tags that all point to the "latest" ref. Some
# platforms get built less frequently, and may not have a build for each git_revision.
# Iterate through all the versions until we find a single one that has a build for
# all platforms.
for ((i=${#versions[@]}-1; i >= 0; i--)); do
  new_version="${versions[$i]}"
  new_version="$(echo "$new_version" | xargs)" # Trim whitespace
  cipd selfupdate-roll -version-file "$jiri_dir/cipd/cipd_client_version" -version "$new_version" && success=true && break || echo "failed with version ${new_version}"
done
if [ "$success" = false ]; then
  exit 1
fi

# The run_script.py recipe sets this environment variable to allow scripts to
# set their own commit messages.
if [ -n "${COMMIT_MESSAGE_FILE+x}" ]; then
  cat > "$COMMIT_MESSAGE_FILE" <<EOF
[cipd] Update Jiri's version of the cipd CLI

This is an automated change that updates Jiri's pinned version of the
'cipd' command-line tool. It's important to use an up-to-date version
the cipd CLI in case because the CIPD backend doesn't guarantee support
for arbitrarily old versions of the cipd CLI.

This change does not require review, just a Code-Review+2 and
Commit-Queue+2.

However, this change should only be submitted by a human during normal
working hours. Due to Jiri's self-updating functionality Jiri changes
roll out automatically to users the next time they run 'jiri update',
so it's important to remain online shortly after submitting this
change to respond in case users report issues.

Generated by 'scripts/update_cipd.sh'.
EOF
fi
